---
apiVersion: v1
kind: LimitRange
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  limits:
  - default:
      cpu: 500m
      memory: 500Mi
    defaultRequest: # this section defines default requests
      cpu: 500m
      memory: 500Mi
    max: # max and min define the limit range
      cpu: "1"
      memory: 1000Mi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container