---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    app: backend
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /Users/abhishekghosh/Desktop/E4R-final/kubernetes-basics/volumes/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  selector:
    matchLabels:
      app: backend
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    # command: ["/bin/sh","-c"]
    # args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvc-1
---

