---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myapp-sc
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  selector:
    matchLabels:
      app: backend
  storageClassName: myapp-sc
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    # command: ["/bin/sh","-c"]
    # args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvc-1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
---
