---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    app: backend
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/nginx/html
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  selector:
    matchLabels:
      app: backend
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteMany
---